// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/try": {
    params: {};
  };
  "/brand": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/learn": {
    params: {};
  };
  "/learn/:slug": {
    params: {
      "slug": string;
    };
  };
  "/oss": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/sales": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/try" | "/brand" | "/contact" | "/learn" | "/learn/:slug" | "/oss" | "/pricing" | "/privacy" | "/sales" | "/terms";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/api+/try.tsx": {
    id: "routes/api+/try";
    page: "/api/try";
  };
  "routes/brand.tsx": {
    id: "routes/brand";
    page: "/brand";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/learn+/_layout.tsx": {
    id: "routes/learn+/_layout";
    page: "/learn" | "/learn/:slug";
  };
  "routes/learn+/$slug.tsx": {
    id: "routes/learn+/$slug";
    page: "/learn/:slug";
  };
  "routes/learn+/_index.tsx": {
    id: "routes/learn+/_index";
    page: "/learn";
  };
  "routes/oss.tsx": {
    id: "routes/oss";
    page: "/oss";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/sales.tsx": {
    id: "routes/sales";
    page: "/sales";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/api+/try": typeof import("./app/routes/api+/try.tsx");
  "routes/brand": typeof import("./app/routes/brand.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/learn+/_layout": typeof import("./app/routes/learn+/_layout.tsx");
  "routes/learn+/$slug": typeof import("./app/routes/learn+/$slug.tsx");
  "routes/learn+/_index": typeof import("./app/routes/learn+/_index.tsx");
  "routes/oss": typeof import("./app/routes/oss.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/sales": typeof import("./app/routes/sales.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
};