// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/mcp.json": {
    params: {};
  };
  "/.well-known/oauth-authorization-server": {
    params: {};
  };
  "/.well-known/oauth-protected-resource": {
    params: {};
  };
  "/.well-known/openapi.json": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/api/status": {
    params: {};
  };
  "/api/try": {
    params: {};
  };
  "/brand": {
    params: {};
  };
  "/compare/:competitor": {
    params: {
      "competitor": string;
    };
  };
  "/compare": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/developers": {
    params: {};
  };
  "/learn": {
    params: {};
  };
  "/learn/:slug": {
    params: {
      "slug": string;
    };
  };
  "/mcp.json": {
    params: {};
  };
  "/openapi.json": {
    params: {};
  };
  "/openapi.yaml": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/sales": {
    params: {};
  };
  "/subprocessors": {
    params: {};
  };
  "/terms": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/mcp.json" | "/.well-known/oauth-authorization-server" | "/.well-known/oauth-protected-resource" | "/.well-known/openapi.json" | "/about" | "/api/status" | "/api/try" | "/brand" | "/compare/:competitor" | "/compare" | "/contact" | "/developers" | "/learn" | "/learn/:slug" | "/mcp.json" | "/openapi.json" | "/openapi.yaml" | "/pricing" | "/privacy" | "/sales" | "/subprocessors" | "/terms";
  };
  "routes/[.]well-known.mcp[.]json.ts": {
    id: "routes/[.]well-known.mcp[.]json";
    page: "/.well-known/mcp.json";
  };
  "routes/[.]well-known.oauth-authorization-server.ts": {
    id: "routes/[.]well-known.oauth-authorization-server";
    page: "/.well-known/oauth-authorization-server";
  };
  "routes/[.]well-known.oauth-protected-resource.ts": {
    id: "routes/[.]well-known.oauth-protected-resource";
    page: "/.well-known/oauth-protected-resource";
  };
  "routes/[.]well-known.openapi[.]json.ts": {
    id: "routes/[.]well-known.openapi[.]json";
    page: "/.well-known/openapi.json";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/api+/status.tsx": {
    id: "routes/api+/status";
    page: "/api/status";
  };
  "routes/api+/try.tsx": {
    id: "routes/api+/try";
    page: "/api/try";
  };
  "routes/brand.tsx": {
    id: "routes/brand";
    page: "/brand";
  };
  "routes/compare+/$competitor.tsx": {
    id: "routes/compare+/$competitor";
    page: "/compare/:competitor";
  };
  "routes/compare+/_index.tsx": {
    id: "routes/compare+/_index";
    page: "/compare";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/developers.tsx": {
    id: "routes/developers";
    page: "/developers";
  };
  "routes/learn+/_layout.tsx": {
    id: "routes/learn+/_layout";
    page: "/learn" | "/learn/:slug";
  };
  "routes/learn+/$slug.tsx": {
    id: "routes/learn+/$slug";
    page: "/learn/:slug";
  };
  "routes/learn+/_index.tsx": {
    id: "routes/learn+/_index";
    page: "/learn";
  };
  "routes/mcp[.]json.ts": {
    id: "routes/mcp[.]json";
    page: "/mcp.json";
  };
  "routes/openapi[.]json.ts": {
    id: "routes/openapi[.]json";
    page: "/openapi.json";
  };
  "routes/openapi[.]yaml.ts": {
    id: "routes/openapi[.]yaml";
    page: "/openapi.yaml";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/sales.tsx": {
    id: "routes/sales";
    page: "/sales";
  };
  "routes/subprocessors.tsx": {
    id: "routes/subprocessors";
    page: "/subprocessors";
  };
  "routes/terms.tsx": {
    id: "routes/terms";
    page: "/terms";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[.]well-known.mcp[.]json": typeof import("./app/routes/[.]well-known.mcp[.]json.ts");
  "routes/[.]well-known.oauth-authorization-server": typeof import("./app/routes/[.]well-known.oauth-authorization-server.ts");
  "routes/[.]well-known.oauth-protected-resource": typeof import("./app/routes/[.]well-known.oauth-protected-resource.ts");
  "routes/[.]well-known.openapi[.]json": typeof import("./app/routes/[.]well-known.openapi[.]json.ts");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/api+/status": typeof import("./app/routes/api+/status.tsx");
  "routes/api+/try": typeof import("./app/routes/api+/try.tsx");
  "routes/brand": typeof import("./app/routes/brand.tsx");
  "routes/compare+/$competitor": typeof import("./app/routes/compare+/$competitor.tsx");
  "routes/compare+/_index": typeof import("./app/routes/compare+/_index.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/developers": typeof import("./app/routes/developers.tsx");
  "routes/learn+/_layout": typeof import("./app/routes/learn+/_layout.tsx");
  "routes/learn+/$slug": typeof import("./app/routes/learn+/$slug.tsx");
  "routes/learn+/_index": typeof import("./app/routes/learn+/_index.tsx");
  "routes/mcp[.]json": typeof import("./app/routes/mcp[.]json.ts");
  "routes/openapi[.]json": typeof import("./app/routes/openapi[.]json.ts");
  "routes/openapi[.]yaml": typeof import("./app/routes/openapi[.]yaml.ts");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/sales": typeof import("./app/routes/sales.tsx");
  "routes/subprocessors": typeof import("./app/routes/subprocessors.tsx");
  "routes/terms": typeof import("./app/routes/terms.tsx");
};